### ISSUE TITLE
String to lower

### ISSUE THREAD

**Issue by ealexjordan** [pubmediamax/Practice-Code#1]
while response!='No' and response!='no' and response!='n' and response!='Yes' and response!='yes' and response!='y':

Looks good, the only slight suggestion I could come up with is that Python has a function for strings that puts them all lowercase. Using that could eliminate at least two of your statements down to one since you wouldn't have to check for "No" and "no."

http://stackoverflow.com/questions/6797984/how-to-convert-string-to-lowercase-in-python

**Comment by pubmediamax** [comment]
Fixed! Thanks!
